version: '3.8'

services:
  robo_python:
    build: ./robo  # pasta onde está o Dockerfile do robô
    container_name: robo_licita
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/meubanco
    volumes:
      - ./robo:/app
    networks:
      - rede_licita

  mongo:
    image: mongo:6
    container_name: mongo_licita
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - rede_licita

volumes:
  mongo_data:

networks:
  rede_licita:
    driver: bridge
